/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#3B82F6",
        "primary-orange": "#FF5A36",
        "on-primary": "#ffffff",
        "primary-container": "#3B82F6",
        "on-primary-container": "#fdfcff",
        "primary-fixed": "#e1e2e8",
        "on-primary-fixed": "#191c20",
        "secondary": "#00E599",
        "on-secondary": "#ffffff",
        "secondary-container": "#dbe3ef",
        "on-secondary-container": "#002112",
        "secondary-fixed": "#dbe3ef",
        "on-secondary-fixed": "#141c24",
        "surface": "#f9f9ff",
        "surface-dim": "#cbdaff",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e9edff",
        "surface-container-high": "#e0e8ff",
        "surface-container-highest": "#d8e2ff",
        "surface-variant": "#d8e2ff",
        "on-surface": "#001a42",
        "on-surface-variant": "#45474a",
        "inverse-surface": "#101317",
        "inverse-on-surface": "#edf0ff",
        "outline": "#76777b",
        "outline-variant": "#c6c6cb",
        "tertiary": "#665d53",
        "tertiary-container": "#7f756b",
        "tertiary-fixed": "#eee0d4",
        "on-tertiary-fixed": "#211a13",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "unit-2xs": "0.25rem",
        "unit-xs": "0.5rem",
        "unit-sm": "0.75rem",
        "unit-md": "1rem",
        "unit-lg": "1.5rem",
        "unit-xl": "2rem",
        "unit-2xl": "2.5rem",
        "unit-3xl": "3.5rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "stat-counter": ["48px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-hero": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-hero-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      }
    }
  },
  plugins: []
};
